### ISSUE TITLE
Authenticate without browser

### ISSUE THREAD

**Issue by xslates** [joshcarty/google-searchconsole#1]
Hi Josh, 

Thank you for a very useful module. I'm incorporating it into a script that: 

(1) downloads Search Console data 
(2) uploads our Search Console data to BigQuery via the pandas-gbq module 
(3) sends an email to recipients with a logging information

Lastly, I want to schedule this script with Cron. 

**Everything works fine except that I need to do the authentication without the browser redirection.**

I'm new to Python so I'm having trouble understanding how to modify the `authenticate()` function. Right now I'm using the `client_config` parameter passing it the path of my JSON credentials (which are in the same folder). However, I'm redirected to authenticate to a new page every time I run the program. Here's the way I'm doing it now:

<img width="484" alt="screen shot 2018-01-09 at 13 38 05" src="https://user-images.githubusercontent.com/8994002/34721278-711e2e94-f542-11e7-8606-955ec9b88856.png">

This also breaks the Cron Scheduler, the script gets run but nothing happens. 

> The above example will use your client configuration file to interactively generate your credentials. If you wish to save your credentials, to avoid going through the OAuth consent screen in the future, you can specify a path to save them by specifying `serialize='path/to/credentials.json`.

Read this paragraph over and over and looked into the code itself but I can't seem to understand this. Google API's documentation is a tad unclear to me as well. Would it be possible to see a simple code example of how I can solve this?

Hope the question is clear.

Thanks in advance!
  
 **P.S**

I've also tried with JSON files for OAuth Client ID and Service Account Keys and get a KeyError: 'token' in the `credentials` parameter.

**Comment by joshcarty** [comment]
Hi Will,

Glad you've found the package useful. Thanks for getting in touch, happy to help!

So the first time you run:

```python
import searchconsole
account = searchconsole.authenticate(client_config="auth.json", serialize="/path/to/save/credentials.json")
```

You'll run through the OAuth consent page to authenticate. That will create your credentials and, because you've specified `serialize`,  it will have saved them as a JSON file in a location you've set (`/path/to/save/credentials.json` in this example).

That means that next time, you can use the `credentials` argument:

```python
import searchconsole
account = searchconsole.authenticate(client_config="auth.json", credentials="/path/to/save/credentials.json")
```

And you'll be able to authenticate without any of the redirecting to a consent page. That should resolve your issue running as a script with cron.

I'll be adding support for Service Accounts in the near future! I also plan to expand the documentation with more details around authenticating and querying.

Let me know if that works for you and I can close the Issue. Hope that's all clear, this is my first open source project!

**Comment by xslates** [comment]
Thank you so much for the quick answer!! 

It solved the issue. The good thing is that I spent the last 3 days digging into the Google APIs and I think I understand them a bit better, but we need wrapper packages. That stuff is confusing. 

I wanted to give you a heads up. In our case, some of our queries contain characters that give this error when we try to upload them to BigQuery.

`UnicodeEncodeError: 'ascii' codec can't encode characters in position 2893-2895: ordinal not in range(128)`

Upon inspection it seems these are characters in other languages (like greek, etc.)  For the time being I got around it by filtering them out, but maybe that's a case for incorporating `utf-8` encoding somewhere in your library for some esotheric characters, I imagine.

**Comment by joshcarty** [comment]
No worries, glad you resolved the authentication issue!

Regarding your error, all queries are `str` objects which, in Python 3, are just sequences of Unicode code points. It's only when you come to write those code points to disk or send them over a network that you'll need to encode them with something like UTF-8.

Looking at your error, somewhere you (or a package you're using) is trying to encode them as ASCII which, like you say, can't encode special characters like Greek. I'm guessing this encoding is done by the BigQuery client or you're first writing the output to disk?

I've done some testing and I'm confident the package can handle special characters: 

```python
>>> report.rows[:3]
>>> [Row(query='加湿器 フィリップス', clicks=1.0, impressions=2.0, ctr=0.5, position=3.0),
...  Row(query='mi-e 呼吸', clicks=1.0, impressions=2.0, ctr=0.5, position=4.0),
...  Row(query='トリロジー 回路交換', clicks=1.0, impressions=1.0, ctr=1.0, position=3.0)]
 ```

Also, I was able to upload queries with special characters to BigQuery by converting a report to a `pandas.DataFrame` and using `to_gbq`.

```python
>>> df = report.to_dataframe()
>>> df.to_gbq(destination_table='dataset.table', project_id='my-project')
```

I think that's the easiest way I've found to get data into BigQuery. I know it's had some [issues](https://github.com/pydata/pandas-gbq/issues/7) in the past writing to newly created tables but it looks like they've recently been fixed. Just make sure you have the latest versions of `pandas` and `pandas-gbq`.

Hope some of that helps!

**Comment by xslates** [comment]
Yea, I'm using the `pandas-gbq package`. The BigQuery step is the one throwing the error. Chasing that error I stumbled upon this [stackoverflow thread](https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20/20334767). Maybe it's useful. I think there's something happening during the upload that messes up with the encoding. When inspecting those positions they didn't have any suspicious characters.

The solution that I used was to encode and decode the `queries` as suggested in the thread. This fixed it. Apparently, this problem has more to do with Python 3 than anything else.

<img width="576" alt="screen shot 2018-01-12 at 09 38 39" src="https://user-images.githubusercontent.com/8994002/34866508-0ca77302-f77d-11e7-9694-6c61778c7a8f.png">

**Comment by joshcarty** [comment]
Agreed, looks like it's a `pandas-gbq` [issue](https://github.com/pydata/pandas-gbq/issues/106) that may have [just been fixed](https://github.com/pydata/pandas-gbq/pull/108). You can wait for it to be merged or try it out with:

`pip3 install git+https://github.com/maxim-lian/pandas-gbq.git#encoding`

My understanding is that the package doesn't explicitly set an encoding when sending to BigQuery so `http.client` [defaults to latin-1](https://github.com/python/cpython/blob/3.6/Lib/http/client.py#L149). This doesn't entirely explain why it's an ASCII encoding error you're getting but they seem related.

Doing the `.encode('ascii', errors=ignore)` will get rid of your queries containing special characters but hopefully the updates to `pandas-gbq` should let you upload them all to BigQuery.

I'm going to close the issue here but let me know if the update to `pandas-gbq` works for you.

Thanks!
